#Get Range of Input Tcpdump File

if [ $# -ne 2 ]; then
    # TODO: print usage
    echo Usage:
    echo ./test_bash tcpdumpfile resultdir
    exit 1
fi

FLOWSENSE=../src/flowsense
TEST_FLOWSENSE=./test_flowsense.py

OUTPUT=$(tcpslice -R $1)

IFS=$'\2' read -ra TEMP < <(tr $'\t\2' $'\2\t' <<<"$OUTPUT")
ITEMS=("${TEMP[@]//$'\t'/$'\2'}")

BEGIN_SLICING_RANGE=$(echo "${ITEMS[2]} - ${ITEMS[1]}" | bc)

BEGIN_SLICING_RANGE=${BEGIN_SLICING_RANGE/.*}



if (($BEGIN_SLICING_RANGE<5000));then
    echo Error: Tcpdump file must have at least a duration of 5000 seconds
    echo Error: Duration of $1 is only $BEGIN_SLICING_RANGE seconds
    exit
fi

#Create is does not exists results directory

mkdir -p $2

#Range of the tcpdump slice in seconds
SLICE_MIN_SIZE=500
SLICE_MAX_SIZE=5000

#Range for the begining of slicing of tcpdump
let "BEGIN_SLICING_RANGE -=SLICE_MAX_SIZE"


#Basic Time Window Sizes
BTW_SIZES=(50 100 200)

for i in "${BTW_SIZES[@]}"
do
begin_slicing=$RANDOM
let "begin_slicing %=BEGIN_SLICING_RANGE"

slice_size=$RANDOM
let "slice_size %=(SLICE_MAX_SIZE-SLICE_MIN_SIZE)"
let "slice_size +=SLICE_MIN_SIZE"


btw_size=$i

echo Begin Slicing $begin_slicing seconds
echo Slice Size $slice_size seconds
echo BTW Size $btw_size seconds

#Get a random tcpdump slice out of ./tcp_thursday_ip_only MIT tcpdump Dataset
tcpslice +$begin_slicing +$slice_size $1 -w $2/slice$btw_size

#Run Flowsense App using the random tcpdump slice and generate the statistics file
$FLOWSENSE -b $btw_size -r $2/slice$btw_size -o $2/stats$btw_size.csv

#Verify that the statistics File generated by the Flowsense App is correct
python $TEST_FLOWSENSE $2/slice$btw_size $btw_size $2/$btw_size $2/stats$btw_size.csv


done
