#Time Window for tcpdump_thursday_ip_only 251015

#Range for the begining of slicing of tcpdump
RANGE1=251015-500

#Range for the size of the slice
RANGE2=5000


for i in 50 100 200
do
begin_slicing=$RANDOM
let "begin_slicing %=RANGE1"

slice_size=$RANDOM
let "slice_size %=RANGE2"
let "slice_size +=400"


btw_size=$i

echo Begin Slicing $begin_slicing seconds
echo Slice Size $slice_size seconds
echo BTW Size $btw_size seconds

#Get a random tcpdump slice out of ./tcp_thursday_ip_only MIT tcpdump Dataset
tcpslice +$begin_slicing +$slice_size ./tcpdump_thursday_ip_only -w ./results_dir/slice$btw_size

#Run Flowsense App using the random tcpdump slice and generate the statistics file
../src/flowsense -b $btw_size -r ./results_dir/slice$btw_size -o ./results_dir/stats$btw_size.csv

#Verufy that the statistics File generated by the Flowsense App is correct
python ./test_flowsense.py ./results_dir/slice$btw_size $btw_size ./results_dir/$btw_size ./results_dir/stats$btw_size.csv


echo +++++++++++++++++++++++++++++++++++++++
done

#flowsense -b 400 -r tcpdump_thursday_ip_only_3000 -o stats1.csv
